name: Deploy Application Pycine-back

on: 
  push:
    branches: [GMS-WEBIV]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        